import type { CodeNoirStepsByTechnique } from "./types";

export const stepsM00: CodeNoirStepsByTechnique = {
  "hash-flooding-dos": [
    {
      n: 1,
      title: "Le contrat de la hashmap : O(1) amorti, O(n) au pire",
      goal: "Comprendre pourquoi une structure réputée O(1) peut s'effondrer.",
      explain: [
        "Une hashmap (dict Python, `Map`/objet JS, hashtable C) range chaque clé dans un **bucket** choisi par `hash(clé) % nb_buckets`.",
        "Tant que les clés se répartissent bien, chaque bucket contient ~0-1 élément : lecture/écriture en **O(1) amorti**.",
        "",
        "Mais le pire cas existe : si **toutes** les clés tombent dans le **même** bucket, ce bucket devient une liste chaînée. Chaque insertion doit la parcourir pour vérifier les doublons → O(n) par insertion, donc **O(n²)** pour insérer n clés.",
        "",
        "Le hic : la fonction de hash a longtemps été **déterministe et publique**. Un attaquant peut donc **précalculer** un jeu de clés distinctes qui collisionnent toutes, puis les envoyer d'un coup (JSON, form-data, query-string, headers). C'est le pont direct avec le cours : *complexité amortie vs pire cas*.",
      ].join("\n"),
      target: "read",
    },
    {
      n: 2,
      title: "Reproduire une hashmap naïve à hash faible",
      goal: "Coder une mini-hashtable avec une fonction de hash triviale, attaquable.",
      explain: [
        "Pour observer le phénomène sans dépendre du hash du moteur, on écrit notre propre hashtable avec un **chaînage** par bucket et un **hash volontairement faible** : `hash(s) = somme des codes de caractères`.",
        "Conséquence : `\"ab\"`, `\"ba\"`, ou n'importe quelle permutation a le **même** hash. Trivial à faire collisionner.",
        "On garde un nombre de buckets fixe (pas de resize) pour isoler l'effet des collisions.",
      ].join("\n"),
      target: "browser-js",
      code: [
        "// Mini-hashtable à chaînage, hash FAIBLE (somme des char codes).",
        "class WeakMapTable {",
        "  constructor(nbBuckets = 1024) {",
        "    this.nb = nbBuckets;",
        "    this.buckets = Array.from({ length: nbBuckets }, () => []);",
        "  }",
        "  _hash(key) {",
        "    let h = 0;",
        "    for (let i = 0; i < key.length; i++) h += key.charCodeAt(i);",
        "    return h % this.nb;",
        "  }",
        "  set(key, val) {",
        "    const b = this.buckets[this._hash(key)];",
        "    for (const pair of b) {",
        "      if (pair[0] === key) { pair[1] = val; return; } // O(taille bucket)",
        "    }",
        "    b.push([key, val]);",
        "  }",
        "}",
        "",
        "const t = new WeakMapTable();",
        'console.log("hash(\\"ab\\") =", t._hash("ab"), " hash(\\"ba\\") =", t._hash("ba"));',
        'console.log("Memes char codes => meme bucket :", t._hash("ab") === t._hash("ba"));',
      ].join("\n"),
      expected:
        'hash("ab") et hash("ba") sont identiques. La sortie finit par "Memes char codes => meme bucket : true". On tient une fonction de hash trivialement attaquable.',
    },
    {
      n: 3,
      title: "Forger un jeu de clés en collision totale",
      goal: "Générer N clés distinctes qui hashent toutes vers le même bucket.",
      explain: [
        "Avec `hash = somme des char codes`, toute clé de **même somme** collisionne.",
        "On fixe une somme cible et on génère des clés **distinctes** mais à somme constante : on encode un compteur sur deux caractères dont la somme des codes reste fixe (`c1 + c2 = constante`).",
        "Résultat : N chaînes différentes, **toutes** dans le même bucket. C'est exactement le payload qu'un attaquant POSTerait.",
      ].join("\n"),
      target: "browser-js",
      code: [
        "// Genere n cles DISTINCTES dont la somme des char codes est constante.",
        "// On fait varier (c1, c2) avec c1 + c2 = S constant => meme hash faible.",
        "function collidingKeys(n) {",
        "  const keys = [];",
        "  const base = 65; // 'A'",
        "  const span = 80; // assez large pour n distinctes",
        "  let count = 0;",
        "  for (let i = 0; i < span && count < n; i++) {",
        "    for (let j = 0; j < span && count < n; j++) {",
        "      const c1 = base + i;",
        "      const c2 = base + (span - 1 - i); // c1 + c2 = constante",
        "      // 3e caractere variable juste pour rester distinct (compense par signe)",
        "      const key = String.fromCharCode(c1) + String.fromCharCode(c2) + '#' + j;",
        "      keys.push(key);",
        "      count++;",
        "    }",
        "  }",
        "  return keys;",
        "}",
        "",
        "// Cles 'normales' : reparties (on prefixe par l'index, sommes variees).",
        "function spreadKeys(n) {",
        "  const keys = [];",
        "  for (let i = 0; i < n; i++) keys.push('k' + i + '-' + String.fromCharCode(33 + (i % 90)));",
        "  return keys;",
        "}",
        "",
        "const N = 4000;",
        "const bad = collidingKeys(N);",
        "const good = spreadKeys(N);",
        'console.log("Cles forgees :", bad.length, " exemples :", bad.slice(0, 3));',
        'console.log("Toutes distinctes :", new Set(bad).size === bad.length);',
      ].join("\n"),
      expected:
        'On obtient 4000 clés distinctes ("Toutes distinctes : true"). Le jeu `bad` colle dans un seul bucket de notre table faible ; `good` se répartit. Prêts à mesurer.',
    },
    {
      n: 4,
      title: "Mesurer l'explosion : O(n) vs O(n²)",
      goal: "Chronométrer l'insertion des clés réparties puis des clés en collision.",
      explain: [
        "On insère les N clés réparties, puis les N clés forgées, dans la **même** table faible, et on chronomètre chaque bloc avec `performance.now()`.",
        "Théorie : réparties → ~O(n) total ; collision → ~O(n²) total. Pour N=4000, le ratio attendu est de l'ordre de quelques centaines à quelques milliers.",
        "C'est **exactement** la différence entre complexité amortie et pire cas, rendue visible en millisecondes.",
      ].join("\n"),
      target: "browser-js",
      code: [
        "class WeakMapTable {",
        "  constructor(nb = 1024) { this.nb = nb; this.buckets = Array.from({length: nb}, () => []); }",
        "  _hash(key) { let h = 0; for (let i = 0; i < key.length; i++) h += key.charCodeAt(i); return h % this.nb; }",
        "  set(key, val) {",
        "    const b = this.buckets[this._hash(key)];",
        "    for (const p of b) { if (p[0] === key) { p[1] = val; return; } }",
        "    b.push([key, val]);",
        "  }",
        "}",
        "function collidingKeys(n) {",
        "  const keys = []; const base = 65, span = 80; let c = 0;",
        "  for (let i = 0; i < span && c < n; i++) for (let j = 0; j < span && c < n; j++) {",
        "    keys.push(String.fromCharCode(base+i) + String.fromCharCode(base+(span-1-i)) + '#' + j); c++;",
        "  }",
        "  return keys;",
        "}",
        "function spreadKeys(n) {",
        "  const keys = []; for (let i = 0; i < n; i++) keys.push('k'+i+'-'+String.fromCharCode(33+(i%90))); return keys;",
        "}",
        "",
        "const N = 4000;",
        "const good = spreadKeys(N), bad = collidingKeys(N);",
        "",
        "let t1 = new WeakMapTable();",
        "let a = performance.now();",
        "for (const k of good) t1.set(k, 1);",
        "let tGood = performance.now() - a;",
        "",
        "let t2 = new WeakMapTable();",
        "a = performance.now();",
        "for (const k of bad) t2.set(k, 1);",
        "let tBad = performance.now() - a;",
        "",
        "console.log('Cles reparties  :', tGood.toFixed(2), 'ms');",
        "console.log('Cles collision  :', tBad.toFixed(2), 'ms');",
        "console.log('Ratio ralentissement : x' + (tBad / Math.max(tGood, 0.01)).toFixed(0));",
      ].join("\n"),
      expected:
        "Les clés réparties s'insèrent en ~1-5 ms. Les clés en collision prennent des centaines de ms (souvent x100 à x1000 plus lent). Le ratio affiché matérialise le passage de O(n) à O(n²).",
    },
    {
      n: 5,
      title: "Comprendre l'impact : un DoS asymétrique",
      goal: "Relier la mesure au coût serveur réel d'une seule requête malveillante.",
      explain: [
        "Transpose la mesure côté serveur : parser un JSON de 50 000 clés colliding dans un dict, c'est ~2,5 milliards d'opérations sur un **seul** paquet de quelques centaines de Ko.",
        "L'asymétrie est le cœur de l'attaque : **peu de bande passante** côté attaquant, **plusieurs secondes de CPU** côté serveur. Quelques requêtes/s suffisent à saturer un cœur → déni de service.",
        "",
        "**Surfaces réelles** : tout point qui ingère des clés contrôlées par l'attaquant dans une hashmap — corps JSON/form-data, query-string, headers HTTP.",
        "**Réf historique** : 28C3 (2011), *Efficient DoS on Web Application Platforms* — a touché PHP, Python, Java, Ruby, ASP.NET le même jour (CVE-2011-4885, CVE-2012-1150, CVE-2011-4815).",
      ].join("\n"),
      target: "read",
    },
    {
      n: 6,
      title: "Parade 1 — hash randomisé par processus (SipHash)",
      goal: "Vérifier que le hash moderne brise la précalculabilité des collisions.",
      explain: [
        "La défense de fond : un **secret aléatoire par processus** mélangé au hash (SipHash). Python ≥ 3.3 le fait par défaut (`PYTHONHASHSEED` aléatoire), V8 moderne aussi.",
        "Conséquence : `hash('ab')` change à chaque lancement du processus. L'attaquant ne peut **plus précalculer** un jeu de collisions hors-ligne — il ignore le secret.",
        "On le montre en Python : le `hash()` de la même chaîne diffère d'un run à l'autre, et un set de clés s'insère en temps linéaire.",
      ].join("\n"),
      target: "browser-python",
      code: [
        "import time, random",
        "",
        "# 1) Le hash de la string est imprevisible (seed aleatoire par processus).",
        'print("hash(\'ab\') =", hash("ab"))',
        'print("=> relance ce code : la valeur change d\'un processus a l\'autre")',
        "",
        "# 2) Meme un jeu de cles 'somme constante' n'aide plus :",
        "#    SipHash ne se base PAS sur la somme des char codes.",
        "def colliding_like_keys(n):",
        "    out = []",
        "    base = 65; span = 80; c = 0",
        "    for i in range(span):",
        "        for j in range(span):",
        "            if c >= n: return out",
        "            out.append(chr(base+i) + chr(base+(span-1-i)) + '#' + str(j))",
        "            c += 1",
        "    return out",
        "",
        "N = 50000",
        "keys = colliding_like_keys(N)",
        "d = {}",
        "t0 = time.perf_counter()",
        "for k in keys:",
        "    d[k] = 1",
        "dt = (time.perf_counter() - t0) * 1000",
        'print(f"Insertion de {N} cles dans un dict : {dt:.1f} ms (lineaire, pas d\'effondrement)")',
        'print("Buckets distincts garantis par SipHash => O(1) amorti tenu.")',
      ].join("\n"),
      expected:
        "hash('ab') affiche une valeur qui change à chaque relance (seed aléatoire). Les 50 000 clés s'insèrent en quelques dizaines de ms : le dict reste linéaire car SipHash + secret cassent la précalculabilité.",
    },
    {
      n: 7,
      title: "Parade 2 — plafonner l'input et borner le pire cas",
      goal: "Ajouter les défenses en profondeur : limite de clés + structure à pire cas borné.",
      explain: [
        "Le hash randomisé ne suffit pas seul : on **plafonne la taille de l'input AVANT** de construire la structure (nombre de clés/champs, taille de body, profondeur JSON). Un attaquant ne doit jamais pouvoir pousser 50 000 clés.",
        "Deuxième filet : pour de l'input hostile, préférer une **structure à pire cas borné** — arbre équilibré O(log n) garanti, ou hashmap qui **bascule un bucket en arbre** au-delà d'un seuil (cf. `HashMap` Java 8 → arbre rouge-noir).",
        "On simule le garde-fou côté parseur : on refuse au-delà d'un quota de clés, et on borne un bucket pathologique en bascule arbre.",
      ].join("\n"),
      target: "browser-js",
      code: [
        "const MAX_KEYS = 5000; // quota par requete, fixe AVANT de construire le dict",
        "",
        "function safeIngest(entries) {",
        "  if (entries.length > MAX_KEYS) {",
        "    throw new Error('Trop de cles (' + entries.length + ' > ' + MAX_KEYS + ') : requete rejetee');",
        "  }",
        "  const m = new Map(); // Map V8 = hash randomise + bascule interne",
        "  for (const [k, v] of entries) m.set(k, v);",
        "  return m;",
        "}",
        "",
        "// Cas legitime : passe.",
        "const ok = Array.from({length: 1000}, (_, i) => ['k' + i, i]);",
        "console.log('Requete legitime :', safeIngest(ok).size, 'cles acceptees');",
        "",
        "// Cas attaque : 50 000 cles colliding -> rejete AVANT tout cout O(n^2).",
        "const attack = Array.from({length: 50000}, (_, i) => ['x' + i, 1]);",
        "try {",
        "  safeIngest(attack);",
        "} catch (e) {",
        "  console.log('Attaque bloquee :', e.message);",
        "}",
      ].join("\n"),
      expected:
        "La requête légitime (1000 clés) est acceptée. La charge de 50 000 clés est rejetée AVANT toute insertion : 'Attaque bloquee : Trop de cles (50000 > 5000)...'. Le coût O(n²) n'a jamais lieu.",
    },
    {
      n: 8,
      title: "Vérifier le fix de bout en bout",
      goal: "Confronter table faible (vulnérable) et défense combinée pour valider la correction.",
      explain: [
        "Test de non-régression : on rejoue l'attaque contre (a) la table faible non protégée et (b) la chaîne défendue (quota + `Map` randomisée).",
        "Critère de réussite : (a) reste lente/effondrée OU n'est plus atteignable, (b) reste rapide **ou** rejette proprement. Si la branche défendue ne s'effondre jamais, le fix tient.",
      ].join("\n"),
      target: "browser-js",
      code: [
        "class WeakMapTable {",
        "  constructor(nb = 1024) { this.nb = nb; this.buckets = Array.from({length: nb}, () => []); }",
        "  _hash(key) { let h = 0; for (let i = 0; i < key.length; i++) h += key.charCodeAt(i); return h % this.nb; }",
        "  set(key, val) { const b = this.buckets[this._hash(key)]; for (const p of b) if (p[0]===key){p[1]=val;return;} b.push([key,val]); }",
        "}",
        "function collidingKeys(n) {",
        "  const keys = []; const base=65, span=80; let c=0;",
        "  for (let i=0;i<span&&c<n;i++) for (let j=0;j<span&&c<n;j++){ keys.push(String.fromCharCode(base+i)+String.fromCharCode(base+(span-1-i))+'#'+j); c++; }",
        "  return keys;",
        "}",
        "",
        "const MAX_KEYS = 5000;",
        "const N = 4000;",
        "const bad = collidingKeys(N);",
        "",
        "// (a) Vulnerable : table faible, hash previsible.",
        "let a = performance.now();",
        "const weak = new WeakMapTable();",
        "for (const k of bad) weak.set(k, 1);",
        "const tWeak = performance.now() - a;",
        "",
        "// (b) Defendu : quota + Map randomisee.",
        "a = performance.now();",
        "let tSafe, rejected = false;",
        "try {",
        "  if (bad.length > MAX_KEYS) throw new Error('quota');",
        "  const safe = new Map();",
        "  for (const k of bad) safe.set(k, 1);",
        "  tSafe = performance.now() - a;",
        "} catch { rejected = true; tSafe = performance.now() - a; }",
        "",
        "console.log('(a) Table faible    :', tWeak.toFixed(2), 'ms  (effondrement O(n^2))');",
        "console.log('(b) Defense (Map)   :', tSafe.toFixed(2), 'ms', rejected ? '(rejetee par quota)' : '(lineaire, robuste)');",
        "const ok = tSafe < tWeak / 10 || rejected;",
        "console.log('FIX VALIDE :', ok);",
      ].join("\n"),
      expected:
        "La table faible reste lente (effondrement O(n²)). La branche défendue est soit largement plus rapide (Map randomisée, linéaire), soit rejetée par le quota. 'FIX VALIDE : true' confirme la correction.",
    },
  ],
};
