// Snippets de code thématiques par module — utilisés par CodeRain
// pour habiller l'ambiance du dashboard avec le contenu du module focused.

export const MODULE_SNIPPETS: Record<number, string[]> = {
  1: [
    "GET /index.html HTTP/1.1",
    "Host: erwin.local",
    "<!DOCTYPE html>",
    "<meta charset=\"utf-8\">",
    "200 OK · Content-Type: text/html",
    "DNS A erwin.io → 1.2.3.4",
    "TLS 1.3 · ChaCha20-Poly1305",
    "Cache-Control: max-age=3600",
  ],
  2: [
    ".container { display: flex; gap: 1rem }",
    "grid-template-columns: repeat(12, 1fr)",
    "<button type=\"submit\" aria-label=\"Envoyer\">",
    "@media (min-width: 768px) { ... }",
    "position: sticky; top: 0",
    ":hover { transform: translateY(-2px) }",
    "rem · em · vw · clamp(1rem, 2vw, 1.5rem)",
    "box-shadow: 0 2px 8px rgba(0,0,0,.2)",
  ],
  3: [
    "const sum = (a, b) => a + b",
    "const [head, ...rest] = arr",
    "Object.entries(obj).map(([k, v]) => ...)",
    "typeof null === 'object' // gotcha",
    "let n = 0; for (const x of items) n++",
    "JSON.parse(JSON.stringify(deep))",
    "Array.from({ length: 10 }, (_, i) => i)",
    "if (value == null) return default",
  ],
  4: [
    "document.querySelector('.cta')",
    "element.addEventListener('click', handler)",
    "e.preventDefault(); e.stopPropagation()",
    "new MutationObserver((muts) => ...)",
    "element.classList.toggle('is-active')",
    "requestAnimationFrame(animate)",
    "element.dataset.value = '42'",
    "getBoundingClientRect()",
  ],
  5: [
    "async function load() { return await fetch(url) }",
    "Promise.all([a, b, c]).then(...)",
    "const res = await fetch('/api/data', { signal })",
    "throw new ApiError(res.status, msg)",
    "for await (const chunk of stream) { ... }",
    "AbortController() → controller.signal",
    "Promise.race([timeout, request])",
    "fetch(url, { method: 'POST', body: JSON.stringify(data) })",
  ],
  6: [
    "function curry(fn) { return (a) => (b) => fn(a, b) }",
    "WeakMap<Element, Subscription>()",
    "Symbol.iterator · Symbol.asyncIterator",
    "Object.freeze(config) · Object.seal(state)",
    "Reflect.has(obj, 'key')",
    "function* fibonacci() { let a=0,b=1; ... }",
    "new Proxy(target, { get, set })",
    "structuredClone(deepObject)",
  ],
  7: [
    "type User = { id: string; email: string }",
    "interface Repository<T> { find(id: string): T | null }",
    "type Maybe<T> = T | null | undefined",
    "function pick<T, K extends keyof T>(obj: T, keys: K[]): Pick<T, K>",
    "as const · satisfies · never",
    "type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E }",
    "type Keys = keyof typeof CONFIG",
    "declare module \"x\" { ... }",
  ],
  8: [
    "vite build · vite preview",
    "import.meta.env.VITE_API_URL",
    "esbuild --bundle --minify",
    "package.json · \"type\": \"module\"",
    "node --experimental-strip-types app.ts",
    "tsx watch src/server.ts",
    "tree shaking · sideEffects: false",
    "pnpm install --frozen-lockfile",
  ],
  9: [
    "function Hero() { return <h1>Title</h1> }",
    "const [count, setCount] = useState(0)",
    "<Button onClick={() => setCount(c => c + 1)} />",
    "{items.map(x => <Item key={x.id} />)}",
    "props.children · React.ReactNode",
    "<input value={v} onChange={e => set(e.target.value)} />",
    "<>{condition && <span>...</span>}</>",
    "createPortal(node, document.body)",
  ],
  10: [
    "useEffect(() => { return () => cleanup() }, [deps])",
    "const data = useMemo(() => compute(x), [x])",
    "const fn = useCallback(() => ..., [])",
    "useRef<HTMLInputElement>(null)",
    "useSyncExternalStore(sub, get, getServer)",
    "function useDebounced(v, ms) { ... }",
    "useContext(ThemeContext)",
    "useReducer(reducer, initialState)",
  ],
  11: [
    "export default async function Page() { ... }",
    "use server · use client",
    "app/[slug]/page.tsx",
    "import { cookies } from 'next/headers'",
    "redirect('/login') · notFound()",
    "<Link href=\"/dashboard\" prefetch />",
    "export const dynamic = 'force-dynamic'",
    "generateMetadata() → Metadata",
  ],
  12: [
    "create((set) => ({ count: 0, inc: () => set(s => ({ count: s.count+1 })) }))",
    "useStore(s => s.user)",
    "dispatch({ type: 'ADD_ITEM', payload })",
    "<Context.Provider value={state} />",
    "subscribe((s, prev) => ...)",
    "createSlice({ name: 'cart', reducers: { ... } })",
    "persist(store, { name: 'app' })",
    "atom · useAtomValue · useSetAtom",
  ],
  13: [
    "tailwind: text-sm · ring-2 · backdrop-blur",
    "@keyframes spin { to { transform: rotate(360deg) } }",
    "transition: all 200ms cubic-bezier(.4,0,.2,1)",
    "container @container (min-width: 480px) { ... }",
    ":has(.is-active) > .label { color: hot }",
    "view-transition-name: card-123",
    "scroll-snap-type: y mandatory",
    "color-mix(in oklch, accent, white 20%)",
  ],
  14: [
    "test('renders', () => { expect(...).toBe(...) })",
    "vi.fn() · vi.spyOn(obj, 'method')",
    "render(<Component />); fireEvent.click(btn)",
    "await screen.findByText('Loaded')",
    "page.locator('[data-testid=submit]').click()",
    "expect(api).toHaveBeenCalledWith({ ... })",
    "describe.concurrent · it.skipIf",
    "msw setupServer({ http })",
  ],
  15: [
    "performance.mark('start') → measure(...)",
    "<Suspense fallback={<Skeleton />}>",
    "React.lazy(() => import('./Heavy'))",
    "Intersection Observer · loading=\"lazy\"",
    "memo(Component, (a, b) => a.id === b.id)",
    "transition: useDeferredValue(query)",
    "Web Vitals · LCP · CLS · INP",
    "navigator.scheduling.isInputPending()",
  ],
  16: [
    "fastify.get('/api/health', async () => ({ ok: true }))",
    "app.register(cors, { origin, credentials: true })",
    "reply.code(401).send({ error: 'UnauthorizedError' })",
    "addHook('preHandler', authMiddleware)",
    "FastifyRequest<{ Body: LoginInput }>",
    "fastify.listen({ port: 3031, host: '0.0.0.0' })",
    "fastify.io → @fastify/websocket",
    "reply.setCookie('s', value, { httpOnly, secure })",
  ],
  17: [
    "SELECT u.* FROM users u JOIN orders o ON o.user_id = u.id",
    "WHERE created_at > NOW() - interval '7 days'",
    "CREATE INDEX idx_users_email ON users (email)",
    "GROUP BY phase HAVING COUNT(*) > 1",
    "EXPLAIN ANALYZE SELECT ...",
    "BEGIN; ... COMMIT;",
    "ON CONFLICT (id) DO UPDATE SET ...",
    "WITH ranked AS (SELECT ..., ROW_NUMBER() OVER (...)) ...",
  ],
  18: [
    "pgTable('users', { id: uuid().primaryKey() })",
    "db.select().from(users).where(eq(users.id, x))",
    "db.insert(modules).values(data).onConflictDoNothing()",
    "relations(users, ({ many }) => ({ orders: many(orders) }))",
    "drizzle-kit generate · push · migrate",
    "schema.users.$inferSelect",
    "and(eq(a, b), gt(c, d))",
    "transaction(async (tx) => { ... })",
  ],
  19: [
    "const hash = await bcrypt.hash(pwd, 12)",
    "jwt.sign({ sub }, secret, { expiresIn: '7d' })",
    "if (!timingSafeEqual(a, b)) throw new Unauthorized()",
    "Content-Security-Policy: default-src 'self'",
    "Set-Cookie: ph_session=...; HttpOnly; Secure; SameSite=None",
    "rate-limit: 5 attempts / 5 min / IP",
    "validate input · escape output · parameterize SQL",
    "SAMEORIGIN · X-Frame-Options · HSTS",
  ],
  20: [
    "const ws = new WebSocket('wss://api/stream')",
    "ws.on('message', (data) => broadcast(data))",
    "fastify.io.on('connection', socket => ...)",
    "new EventSource('/api/sse') · onmessage",
    "Server-Sent Events · text/event-stream",
    "channel.publish('room:42', payload)",
    "binary frames · MessageChannel · postMessage",
    "redis.subscribe('chan') · publish('chan', msg)",
  ],
  21: [
    "FROM node:22-alpine AS runtime",
    "docker build -f apps/api/Dockerfile -t api .",
    "docker compose --env-file .env.prod up -d",
    "github actions: on: push: branches: [main]",
    "uses: actions/checkout@v4",
    "kubectl apply -f deployment.yaml",
    "healthcheck: pg_isready -U $POSTGRES_USER",
    "secrets · GITHUB_TOKEN · DEPLOY_KEY",
  ],
  22: [
    "wrangler publish · cloudflare workers",
    "vercel deploy --prod",
    "S3 PutObject · presigned URL",
    "Lambda · Edge Functions · Pages Functions",
    "CDN · Cache-Control: public, max-age=31536000",
    "DNS A record · CNAME · proxied",
    "WAF rule: rate-limit /login",
    "us-east-1 · eu-west-3 · ap-southeast-1",
  ],
  23: [
    "new THREE.Mesh(geometry, material)",
    "useFrame((state, delta) => mesh.current.rotation.y += delta)",
    "<Canvas><ambientLight /><mesh>...</mesh></Canvas>",
    "useGLTF('/models/scene.glb')",
    "OrbitControls · PerspectiveCamera",
    "shader: gl_FragColor = vec4(color, 1.0)",
    "instancedMesh · 10k objects · 60fps",
    "post-processing: bloom · vignette · grain",
  ],
  24: [
    "const embedding = await voyage.embed(text)",
    "vector(1024) · cosine similarity · pgvector",
    "SELECT id FROM chunks ORDER BY embedding <=> $1 LIMIT 5",
    "chunking: recursive · semantic · fixed-size",
    "RAG: retrieve → augment → generate",
    "reranking with cross-encoder",
    "hybrid search: BM25 + dense vectors",
    "context window: 200k tokens · cache TTL: 5min",
  ],
  25: [
    "anthropic.messages.create({ model: 'claude-opus-4-7', ... })",
    "tool_use: { name: 'search', input: { query } }",
    "extended thinking · budget_tokens: 8000",
    "stream: true · for await (const chunk of stream) { ... }",
    "MCP server: stdio · server.tool('search', schema, fn)",
    "agent loop: think → act → observe → repeat",
    "prompt caching · cache_control: { type: 'ephemeral' }",
    "claude code · /skill · slash commands · hooks",
  ],
};

// Fallback générique si on n'a pas de mapping (ne devrait pas arriver)
export const GENERIC_SNIPPETS: string[] = [
  "// Porterfield Heroes · workshop n°1",
  "while (motivated) { learn(); ship(); }",
  "git commit -m 'feat: another step'",
  "const journey = [...modules].reduce(...)",
  "console.log('Day', streak, '· keep going')",
];

export function getSnippetsForModule(moduleNumber: number | null): string[] {
  if (moduleNumber === null) return GENERIC_SNIPPETS;
  return MODULE_SNIPPETS[moduleNumber] ?? GENERIC_SNIPPETS;
}
